[release]
version = ""
date = 1970-01-01
update = true

[data]
alphafold = ""
metacyc = ""
path = ""
tmp = ""

[databases]
interpro.production = ""
interpro.staging = ""
interpro.release = ""
interpro.fallback = ""
iprscan.production = ""
goa = ""
intact = ""
pdbe = ""
pfam = ""
uniprot = ""

[elasticsearch]
hx.nodes = [ "hx-node1", "hx-node2" ]
hx.user = ""
hx.password = ""
hx.fingerprint = ""
hl.nodes = [ "hl-node1", "hl-node2" ]
hl.user = ""
hl.password = ""
hl.fingerprint = ""

[exchange]
ebisearch = ""
goa = ""
interpro = ""

[workflow]
path = ""
scheduler = ""
